### ISSUE TITLE
Proper boolean type for OperatorEq

### ISSUE THREAD

**Issue by tim-vandecasteele** [bseddon/XPath20#1]
👋 it's been a while 😂 

I was trying the code with an updated Belgium tax taxonomy, where there's an assertion like this

```xml
<variable:precondition
	xlink:type="resource"
	xlink:label="pre_ExistCOVID19AidTemporary"
	test="(string($COVID19AidTemporaryAdjustmentPrepaymentsCalculation) eq 'true')">
</variable:precondition>
```

in my previous proposed change https://github.com/tim-vandecasteele/xbrl-experiment/commit/b976b6cb01f9e2860adc2379448076119b1bef2e I fixed similar tests, but they were always a combination of multiple tests (for example `(string($ModifiedClosingDateTaxPeriodFrom2017-07-26ForeignCompany) eq 'false') and
	(string($COVID19AidTemporaryAdjustmentPrepaymentsCalculation) eq 'true')`).

The change I proposed earlier doesn't work with single statements as it doesn't return a `CoreFuncs::BooleanValue`. As such I would propose to change it to:

```php
else if ( $typeA == Types::$BooleanType || $typeB == Types::$BooleanType ) {
	return CoreFuncs::BooleanValue(CoreFuncs::BooleanValue($a) == CoreFuncs::BooleanValue($b));
}
```

Let me know if you need additional information or a specific test case.

**Comment by bseddon** [comment]
Hi Tim

Thanks for the update.  Your suggested change makes sense, has been applied and will be used in the nightly tests tonight.  Assuming the tests complete successfully I'll commit the change in the morning.

Best wishes

Bill Seddon

**Comment by tim-vandecasteele** [comment]
Great, thanks!

If it doesn't succeed, let me know and I can look further into it.

**Comment by bseddon** [comment]
As expected, the change to not result in an new errors during the overnight tests so it has been pushed to the master branch.

Thanks for your effort identifying and fixing the issue.

**Comment by tim-vandecasteele** [comment]
My pleasure ☺️
